import random
from faker import Faker
import logging

fake = Faker()

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')

def generate_customer():
    return {
        "id": fake.uuid4(),
        "name": fake.name(),
        "phone": fake.phone_number(),
        "email": fake.email()
    }

def generate_dialogue(total_lines=500):
    """
    Generate a natural scenario-based dialogue with alternating customer and bank lines.
    total_lines: total lines in dialogue (should be even).
    """

    # Ensure even number of lines
    if total_lines % 2 != 0:
        total_lines += 1

    scenarios = {
        "fraud": {
            "customer": [
                "I noticed a suspicious charge on my account I didn't make.",
                "Can someone help me? I think my account was hacked.",
                "There are withdrawals that I don't recognize at all.",
                "Please freeze my account right away.",
                "I'm really worried about possible identity theft.",
                "Why was my card declined yesterday without reason?",
                "My balance dropped suddenly, and I don't know why.",
                "I never authorized these payments appearing here.",
                "There was a login from a location I don’t recognize.",
                "Is it possible to reverse these unauthorized charges?",
                "I received alerts about large transfers I never made.",
                "The fraud department contacted me but I need details.",
                "How do I dispute these charges effectively?",
                "Is my personal data safe with you?",
                "Someone changed my phone number on file without permission.",
                "I got a call saying my account is compromised, is that true?",
                "How long will your investigation take?",
                "Can you send me a formal fraud report by email?",
                "I want to close my account because of this fraud.",
                "What steps can I take to secure my account better?",
                "There’s a charge from overseas that I didn’t authorize.",
                "My recent statements show transactions I never made.",
                "I haven't received my replacement card after reporting fraud.",
                "Why are there fees on my account I never agreed to?",
                "Can I get a new account number to prevent further fraud?",
                "I want to activate fraud alerts on all my accounts.",
                "I suspect someone is stealing my identity.",
                "My credit score dropped unexpectedly and I’m concerned.",
                "I keep getting suspicious emails pretending to be the bank.",
                "There was an attempt to reset my password without me.",
                "How can I prevent fraud from happening again?",
                "Are there any unusual charges on my account I should check?",
                "What’s the process to recover money lost to fraud?",
                "I’m worried someone took out loans in my name.",
                "My card was blocked suddenly without any prior notice.",
                "Can I speak directly with your fraud investigation team?",
                "How do you keep my sensitive data protected?",
                "Is two-factor authentication an option for me?",
                "I think my social security number has been compromised.",
                "I see fraudulent purchases on my credit card statement.",
                "I want to dispute ATM withdrawals I never made.",
                "My account was accessed outside of normal hours.",
                "I believe my card was cloned somehow.",
                "What exactly does your fraud protection cover?",
                "Can you verify recent transactions with me?",
                "I received a letter about suspicious account activity.",
                "Why was my card temporarily disabled?",
                "Can I get fraud alerts via text message?",
                "Are there any limits on transactions I can dispute?",
                "How long do fraud investigations usually take?",
                "I want to update my contact info after this incident.",
                "Please help me secure my account as soon as possible.",
                "I noticed suspicious login attempts in my history.",
                "Can you explain what triggers account freezes?",
                "What should I do if I receive phishing emails?",
                "Are there ways to get early fraud warnings?",
                "What’s your policy on reimbursing fraudulent charges?",
                "How do I check if my identity info has been leaked?",
                "Can I freeze my credit temporarily?",
                "Do you offer credit monitoring services?",
                "Are my online transactions secure with your bank?",
                "What happens if fraud occurs again after I report?",
                "Can I report fraud through your mobile app?",
                "Is there a dedicated fraud hotline I can call anytime?",
                "How often do you update your security measures?",
                "What happens if my card gets stolen again?",
                "Can I get assistance with identity restoration?",
                "Do you have partnerships with credit bureaus for fraud?",
                "What should I do if I lose my phone linked to banking?",
                "How can I spot fraudulent emails or texts?",
                "Do you provide training or tips for fraud prevention?",
                "Is biometric authentication supported?",
                "Can I lock my card temporarily through the app?",
                "Are international transactions monitored differently?",
                "What’s the protocol if fraud is detected after business hours?",
                "Can I authorize only small transaction limits?",
                "Do you offer any insurance for fraud losses?",
                "How does your fraud detection system work?",
                "What information do I need to provide during investigation?",
                "Can you explain chargebacks related to fraud?",
                "What records will you keep about my fraud case?",
                "Can fraud impact my credit score directly?",
                "How quickly will my card be replaced after fraud?",
                "Are refunds automatic or do I need to file claims?",
                "How do I verify the legitimacy of bank communications?",
                "What’s the best way to protect my online banking login?",
                "Are there known fraud scams circulating currently?",
                "How do you handle false positive fraud alerts?",
                "Will I get a temporary card during the investigation?",
                "How can I track the progress of my fraud case?",
                "What’s your contact info for urgent fraud assistance?",
            ],
            "bank": [
                "Thank you for contacting us. Please provide your account number.",
                "I'm reviewing your transaction history now.",
                "We will start an investigation immediately.",
                "Your account has been temporarily frozen to protect you.",
                "Please monitor your account and report any new suspicious activity.",
                "Have you shared your login credentials recently?",
                "We recommend you change your password as soon as possible.",
                "Would you like me to connect you to our fraud specialist?",
                "After investigation, unauthorized charges will be reimbursed.",
                "Thank you for your patience while we work on this.",
                "We've detected suspicious login attempts and blocked those sessions.",
                "Your personal data is secured using industry-standard encryption.",
                "A detailed fraud report can be sent to your registered email.",
                "I've escalated your case to the fraud department for immediate action.",
                "Enabling two-factor authentication will add extra security.",
                "Regularly checking your credit report can help detect identity theft.",
                "You can opt to receive alerts via SMS or email.",
                "Your account is now flagged for enhanced monitoring.",
                "Investigations typically take 7-10 business days.",
                "Please verify any recent transactions you made with us.",
                "Your replacement card will be mailed to your address shortly.",
                "Unauthorized fees have been reversed on your account.",
                "You can request a new account number if you prefer.",
                "Fraud alerts can be customized in your online banking settings.",
                "If you suspect identity theft, consider placing a credit freeze.",
                "Our fraud specialists are available 24/7 to assist you.",
                "Your concerns have been recorded in our system.",
                "Please update your contact info if it has changed.",
                "Disputes can be initiated through our mobile app.",
                "Our security team constantly monitors for suspicious activity.",
                "We advise using strong, unique passwords for your accounts.",
                "I will send instructions on securing your account.",
                "Your account has been locked temporarily as a precaution.",
                "Please avoid sharing your account details with anyone.",
                "We blocked all suspicious IP addresses accessing your account.",
                "Your Social Security number is protected under strict policies.",
                "You can enroll in our identity theft protection services.",
                "We will notify you immediately if we detect suspicious activity.",
                "Unauthorized transactions are not your responsibility.",
                "Thank you for reporting this promptly.",
                "Please confirm recent transactions so we can verify.",
                "We will keep you updated throughout the investigation.",
                "Your cooperation is important to resolve this quickly.",
                "Contact us immediately if you notice new suspicious activity.",
                "We take fraud protection seriously and regularly update our systems.",
                "Check your email for tips on preventing fraud.",
                "Spending limits can be set to protect your account.",
                "Your account security is our top priority.",
                "We're here to support you through this process.",
                "Please review our recommended security best practices.",
                "Our team is available if you need further assistance.",
                "You can freeze your credit by contacting major bureaus.",
                "We offer credit monitoring for an additional fee.",
                "Using biometrics can enhance your account security.",
                "You can temporarily lock your card through the app.",
                "International transactions are monitored with extra scrutiny.",
                "Alerts outside business hours trigger immediate reviews.",
                "Small transaction limits can reduce fraud risk.",
                "We offer fraud loss insurance for eligible accounts.",
                "Our fraud detection uses advanced machine learning models.",
                "You’ll need to provide identification during the investigation.",
                "Chargebacks can be requested for fraudulent transactions.",
                "All details of your case will be documented securely.",
                "Fraud itself does not directly affect your credit score.",
                "Replacement cards are issued within 5 business days.",
                "Refunds require claim submission but are processed promptly.",
                "Verify bank communications by contacting our official numbers.",
                "Use strong passwords and avoid public Wi-Fi for online banking.",
                "Be aware of common phishing and scam tactics.",
                "False positives can occur, and we work to minimize them.",
                "Temporary cards may be issued during investigations.",
                "Track your fraud case status via online banking.",
                "Contact our hotline anytime for urgent fraud help.",
                "We appreciate your vigilance in protecting your account.",
                "Security questions and biometric locks add protection.",
                "Avoid clicking links from unknown emails or texts.",
                "Your feedback helps us improve our fraud prevention.",
                "We recommend regular updates of your security software.",
                "Account freezes can be lifted once fraud is resolved.",
                "Notify us if you lose devices linked to your account.",
                "We provide educational resources on fraud prevention.",
                "Multi-factor authentication is highly recommended.",
                "Alerts can be tailored based on your transaction patterns.",
                "We monitor accounts continuously for suspicious activity.",
                "Please ensure your contact info is current for alerts.",
                "Keep a list of recent transactions for easy verification.",
                "Our fraud team works closely with law enforcement agencies.",
            ]
        },
        "card_issue": {
            "customer": [
                "My debit card isn't working at the ATM.",
                "I lost my credit card; what should I do?",
                "Can you send me a replacement card?",
                "My card got declined during a purchase.",
                "I think my card was swallowed by the ATM.",
                "How long does it take to receive a new card?",
                "I noticed a chip malfunction on my card.",
                "Is there a fee for getting a new card?",
                "Can I pick up my replacement card at a branch?",
                "My card expired but I didn't get a new one.",
                "Can I temporarily freeze my card online?",
                "What are the steps to report a stolen card?",
                "Can I use a digital card until my physical one arrives?",
                "Why was my card blocked without notification?",
                "I need a card with a higher daily withdrawal limit.",
                "How do I update my card PIN?",
                "Can I change my card type to a rewards card?",
                "My card was declined even though I have funds.",
                "What happens if my card is lost overseas?",
                "Can I order multiple cards on one account?",
                "Are contactless payments available on my card?",
                "How secure is using my card online?",
                "My card number was compromised in a data breach.",
                "Can you cancel my current card and issue a new one?",
                "I want to set spending limits on my card.",
                "How do I activate my new card?",
                "My card got damaged; can I get a replacement?",
                "Can I use my card internationally without extra fees?",
                "Is there a notification service for card transactions?",
                "How do I check if my card is enabled for contactless?",
                "Can I get a virtual card for online purchases?",
                "Why did my card suddenly stop working?",
                "What to do if my card was used without my permission?",
                "Is my card linked to my mobile wallet?",
                "How can I update the mailing address for my card?",
                "Are there fees for expedited card delivery?",
                "Can I temporarily disable my card through the app?",
                "What to do if I forget my card PIN?",
                "Can I request a card with a custom design?",
                "Are there cards specifically for travel benefits?",
                "How do I dispute charges on my card statement?",
                "Can I set alerts for transactions over a certain amount?",
                "My card got blocked after multiple wrong PIN attempts.",
                "Can I add an authorized user to my card?",
                "How does chip-and-PIN differ from swipe cards?",
                "What is the process for replacing a lost card?",
                "Can I use my card to withdraw cash at convenience stores?",
                "Are there limits on contactless payments?",
                "How do I protect my card information online?",
                "What to do if my card was cloned?",
                "Can I get cashback using my card at stores?",
                "Is there a reward program tied to my card?",
                "How do I enroll in paperless statements?",
                "What happens if my card is declined overseas?",
                "Can I set a temporary spending freeze on my card?",
                "Are chip-enabled cards more secure?",
                "How to activate my card after receiving it?",
                "My card was declined despite having credit available.",
                "How do I change my billing address?",
                "Can I use my card for subscription services?",
                "What’s the daily withdrawal limit on my card?",
                "Are there travel insurance benefits with my card?",
                "Can I order additional cards for family members?",
                "How do I protect my card from fraud?",
                "Is contactless payment secure?",
                "Can I use my card with mobile payment apps?",
                "How do I report suspicious card activity?",
                "My card was retained by an ATM; what next?",
                "How soon can I get a replacement after reporting lost card?",
                "Are there fees for international transactions?",
                "Can I get alerts for card usage in foreign countries?",
                "What documents do I need to replace a lost card?",
                "How to change my card's PIN securely?",
                "Can I get a temporary card instantly at a branch?",
                "Are virtual cards accepted everywhere?",
                "What security features does my card have?",
                "How do I deactivate my old card after replacement?",
                "What to do if my card is damaged beyond use?",
                "Can I request a card with enhanced security features?",
                "Are there prepaid card options?",
                "How to report unauthorized card charges?",
                "Can I get a card for business use?",
                "Are there benefits for using my card frequently?",
                "How do I check recent card transactions online?",
                "Can I link multiple cards to one account?",
                "What is the expiration period of my card?",
                "How do I safely dispose of my old card?",
            ],
            "bank": [
                "We can block your card immediately to prevent misuse.",
                "Please provide your card number or account details.",
                "Replacement cards typically arrive within 5-7 business days.",
                "There is no fee for standard replacement cards.",
                "You can pick up a new card at any branch if preferred.",
                "We can issue an expedited card for an additional fee.",
                "Your card has been temporarily frozen as requested.",
                "To activate your new card, call the number on the sticker.",
                "PIN changes can be done through your online banking.",
                "Contactless payments are available if your card supports it.",
                "We recommend using strong PINs and not sharing them.",
                "International use may require prior notification.",
                "Virtual cards are available for secure online shopping.",
                "Lost or stolen cards should be reported immediately.",
                "You can set spending limits via our mobile app.",
                "Damaged cards can be replaced free of charge.",
                "Your card number will change with replacement cards.",
                "Authorized users can be added by request.",
                "Cards are chip-enabled for enhanced security.",
                "Daily withdrawal limits vary by account type.",
                "Alerts can be set for transactions over specified amounts.",
                "We recommend enrolling in paperless statements for security.",
                "Mobile wallet linking is supported for most cards.",
                "Expired cards are automatically replaced before expiry date.",
                "Please avoid sharing card details via email or phone.",
                "ATM withdrawals are available 24/7 with your card.",
                "We offer cards tailored for travel, rewards, or business.",
                "Charges for expedited shipping will appear on your statement.",
                "Forgotten PINs can be reset via our secure process.",
                "Cards blocked after wrong PIN attempts can be unlocked at branches.",
                "You can temporarily disable your card via our app.",
                "Our cards come with fraud protection services.",
                "To dispute charges, submit a claim online or call support.",
                "Cashback offers depend on your card type.",
                "International transaction fees vary; check your card terms.",
                "We recommend notifying us before traveling abroad.",
                "Our customer service can guide you through card issues anytime.",
                "You can receive text or email notifications for card activity.",
                "Replacing a lost card cancels the old one automatically.",
                "Virtual cards can be generated instantly for online use.",
                "Cards with custom designs are available upon request.",
                "Travel insurance benefits apply to select card types.",
                "Unauthorized charges are investigated promptly.",
                "Ensure your contact info is up to date for notifications.",
                "Cards are equipped with EMV chips for fraud prevention.",
                "You can use your card for subscriptions and recurring payments.",
                "Security features include CVV codes and transaction alerts.",
                "Our fraud team monitors unusual card activity 24/7.",
                "You can set transaction limits for added security.",
                "Prepaid cards are available for specific use cases.",
                "We provide educational resources on safe card use.",
                "Please securely dispose of old or damaged cards.",
                "Replacing your card may require identity verification.",
                "Business cards come with additional controls and benefits.",
                "You can view recent transactions in real time online.",
                "Linking multiple cards to your account is possible.",
                "Cards expire every 3-5 years depending on type.",
                "Contact support immediately if you notice suspicious activity.",
                "You can schedule a card delivery to an alternative address.",
                "Lost cards are blocked instantly to prevent fraud.",
                "PIN changes help keep your card secure.",
                "Temporary cards may be issued at branches.",
                "Some merchants may not accept virtual cards.",
                "Use our mobile app for the easiest card management.",
                "Chip-and-PIN cards provide higher security than swipe cards.",
                "Card designs and benefits vary by account type.",
                "Contactless payments are secure with proper precautions.",
                "We can help set up automatic alerts for your spending.",
                "You can add additional cards for family or employees.",
                "Card expiration reminders will be sent automatically.",
                "Always check your statements regularly for unusual charges.",
                "You can protect your card info by using strong passwords.",
                "Please avoid using public Wi-Fi for card transactions.",
                "Lost or stolen cards should be reported immediately to avoid liability.",
                "Our fraud detection system helps protect your card use.",
                "Mobile payments are supported by most modern cards.",
                "You can freeze and unfreeze your card anytime via our app.",
                "Use biometric authentication when available for added security.",
                "Contact our customer support if you need assistance anytime."
            ]
        },
        "login_problem": {
            "customer": [
                "I can't log into my online banking account.",
                "My password seems to be rejected even though it's correct.",
                "How do I reset my forgotten password?",
                "I think my account is locked due to multiple failed attempts.",
                "Can you help me recover my username?",
                "I didn't receive the verification code for two-factor authentication.",
                "Is there a way to bypass the login temporarily?",
                "I got an error message saying 'account suspended.'",
                "How long does it take to unlock a locked account?",
                "Can I reset my password over the phone?",
                "I forgot my security questions answers.",
                "What can I do if I lost access to my email?",
                "I received a notification about suspicious login attempts.",
                "Why am I asked for additional verification suddenly?",
                "Can I set up biometric login on my account?",
                "How do I enable or disable two-factor authentication?",
                "Is it possible to get a temporary password?",
                "I suspect someone else accessed my account.",
                "Can you check recent login activity for me?",
                "How do I change my registered phone number for verification?",
                "I tried logging in from a new device but was blocked.",
                "What should I do if I forgot my password and email?",
                "Can I use my mobile number to log in instead of email?",
                "I keep getting captcha errors during login.",
                "How do I update my security settings online?",
                "Is there a way to recover my account if my phone is lost?",
                "Can I use social media login options with your bank?",
                "What should I do if the website is not loading properly?",
                "I want to deactivate my account temporarily.",
                "Are there limits on login attempts before locking?",
                "Can I get notified of failed login attempts?",
                "How do I secure my account from unauthorized access?",
                "Is there an app I can use to manage login settings?",
                "Can I reset my password without email or phone access?",
                "What identification do I need to verify account ownership?",
                "How do I remove old devices from my account?",
                "Why is my account asking for verification after every login?",
                "Can I disable auto-login on my devices?",
                "What are common reasons for login failures?",
                "How to avoid phishing scams targeting login info?",
                "Is my password stored securely?",
                "How often should I change my password?",
                "What do I do if I suspect my account was hacked?",
                "Can I set up login alerts for security?",
                "Is there a way to recover a deleted account?",
                "How do I manage trusted devices?",
                "Can I contact support for login help 24/7?",
                "What is the minimum password length requirement?",
                "Can I use password managers with your site?",
                "How do I update my email address linked to my account?",
                "Are security questions still used for verification?",
                "What happens if I exceed login attempts?",
                "Can I enable biometric login on multiple devices?",
                "Why is two-factor authentication important?",
                "Is SMS verification safe?",
                "What should I do if I lose my phone with authentication app?",
                "How do I log out remotely from all devices?",
                "Can I get a backup code for authentication?",
                "Are there alternatives to SMS for two-factor?",
                "Can I trust emails asking me to verify login?",
                "How do I secure my account on public computers?",
                "Are there any known outages affecting login?",
                "How do I report suspicious login activity?",
                "Can I access my account via telephone banking?",
                "How can I improve my account security settings?",
                "What do I do if I suspect a data breach?",
                "Is it safe to save my password in browsers?",
                "How do I check if my account is locked?",
                "Can you help me regain access to my account?",
                "How long is a password reset link valid?",
                "Can I update my login preferences online?",
                "What is the process for account recovery?",
                "Are there differences between web and mobile login?",
                "How can I set up trusted contacts for account recovery?",
                "Is face recognition login available?",
                "What should I do if I can't receive SMS codes?",
                "Are there limits on password reset requests?",
                "How do I prevent brute force attacks on my account?",
                "Can I monitor active sessions on my account?",
                "What actions trigger account lockouts?",
                "Are there help guides for login problems on your site?",
                "Can I reset my password using security questions?",
                "What do I do if I forgot both email and phone access?"
            ],
            "bank": [
                "Let's start by verifying your identity. Can you provide your full name and account number?",
                "I can assist you with resetting your password. I'll send a reset link to your registered email.",
                "Your account appears to be locked due to multiple failed login attempts. We can unlock it after verifying your identity.",
                "Please check your spam folder for the two-factor authentication code.",
                "You can reset your password using the 'Forgot Password' link on the login page.",
                "For security, we require verification via phone or email before resetting credentials.",
                "Temporary password generation is possible after successful identity verification.",
                "I'll review your recent login activity and alert you of any suspicious attempts.",
                "Biometric login can be enabled in the app settings for faster access.",
                "Please update your registered phone number in your profile settings.",
                "You may unlock your account by answering your security questions.",
                "If you lost access to your email, please provide alternate verification details.",
                "We recommend enabling two-factor authentication to enhance your account security.",
                "Login attempts from unrecognized devices trigger additional verification steps.",
                "You can disable auto-login on devices from your security settings page.",
                "Multiple failed attempts can lock your account for up to 30 minutes.",
                "Our support team is available 24/7 to assist with login issues.",
                "We advise using password managers to keep your credentials secure.",
                "Your password is stored using strong encryption methods.",
                "If you suspect unauthorized access, please change your password immediately.",
                "Login alerts can be configured to notify you of account access.",
                "You can remove old or unused devices from your trusted device list.",
                "Backup codes for two-factor authentication can be generated in your profile.",
                "You may request account recovery assistance by verifying your identity over the phone.",
                "Using trusted networks and avoiding public Wi-Fi increases login security.",
                "We recommend changing your password every 3-6 months.",
                "Password reset links expire after 15 minutes for your protection.",
                "Security questions are used as an additional layer of verification.",
                "If you haven't received your verification code, try resending or check your contact info.",
                "Your account will be locked after 5 consecutive failed login attempts.",
                "You can monitor active sessions and log out remotely if needed.",
                "Face recognition login is available on supported devices.",
                "If you lose your phone, please disable two-factor authentication temporarily.",
                "We do not support social media login options currently.",
                "Our website and app undergo regular security updates to protect your data.",
                "If you experience repeated captcha errors, clearing your browser cache may help.",
                "You can contact support to deactivate your account temporarily.",
                "SMS verification codes are valid for 10 minutes after issuance.",
                "Please be cautious of phishing attempts asking for your login details.",
                "Password managers can safely store your credentials and generate strong passwords.",
                "We recommend logging out of accounts on shared devices.",
                "Your login preferences can be updated in the account settings.",
                "Two-factor authentication significantly reduces the risk of unauthorized access.",
                "We monitor for unusual login behavior to protect your account.",
                "You can enable login alerts for every access or only suspicious ones.",
                "Our support staff will never ask for your password directly.",
                "If you suspect a breach, we recommend resetting all your passwords.",
                "You can log in using your mobile number if it's linked to your account.",
                "Recovery processes require verifying multiple identity factors for security.",
                "Login problems can often be resolved by clearing cookies and cache.",
                "You can generate backup codes to use when your primary device is unavailable.",
                "Please ensure your contact information is always up to date for smooth verification.",
                "Our fraud department handles cases of suspected unauthorized account access.",
                "The minimum password length is 8 characters, including letters and numbers.",
                "You can check your account lock status in the security section of online banking.",
                "We encourage using strong, unique passwords not used on other sites.",
                "If you forgot both email and phone access, contact support for manual verification.",
                "Account recovery may require photo ID and security question confirmation.",
                "Temporary account lockouts are security measures to protect your funds.",
                "You can disable biometric login anytime via your device settings.",
                "Multi-factor authentication options include SMS, email, and authentication apps.",
                "Keep your security questions answers private and hard to guess.",
                "We recommend regular security audits of your online banking account.",
                "If you notice login attempts from unknown locations, report them immediately.",
                "Avoid saving passwords in browsers on shared devices.",
                "For help with login issues, our website has step-by-step guides and FAQs.",
                "If your account was suspended, contact support for details and resolution.",
                "We can send verification codes again if not received initially.",
                "Temporary passwords expire after first use for safety.",
                "Please be cautious of fake websites mimicking our login page.",
                "Our systems are monitored 24/7 for suspicious activities.",
                "You can access your account via phone banking with identity verification.",
                "Trusted contacts can be set up to help in account recovery.",
                "Face recognition login improves security and convenience.",
                "If SMS codes don't arrive, check with your mobile carrier.",
                "We log all login attempts for security auditing purposes.",
                "Please avoid phishing scams and never share your password.",
                "You can change your email linked to the account through profile settings.",
                "We recommend biometric login for enhanced security.",
                "If you suspect hacking, immediately update your password and notify us.",
                "Temporary account suspension is usually resolved after verification.",
                "You can check recent login activity from your security dashboard.",
                "Our app supports multi-device login and secure sessions.",
                "Password reset requests have limits to prevent abuse.",
                "Contact our fraud team if you notice any suspicious activity.",
                "You can manage your login alerts and preferences online.",
                "We do not currently support login via social media accounts.",
                "You can recover deleted accounts within a limited time by contacting support."
            ]
        }
    }

    # Select scenario randomly
    scenario_name = random.choice(list(scenarios.keys()))
    customer_lines = scenarios[scenario_name]["customer"]
    bank_lines = scenarios[scenario_name]["bank"]

    logging.info(f"Selected scenario: {scenario_name}")

    dialogue = []
    cust_idx = 0
    bank_idx = 0

    # Alternate customer and bank lines until total_lines reached
    for i in range(total_lines):
        if i % 2 == 0:
            # Customer turn
            line = customer_lines[cust_idx]
            cust_idx = (cust_idx + 1) % len(customer_lines)
            dialogue.append(f"Customer: {line}")
        else:
            # Bank turn
            line = bank_lines[bank_idx]
            bank_idx = (bank_idx + 1) % len(bank_lines)
            dialogue.append(f"Bank Employee: {line}")

    return "\n".join(dialogue)


if __name__ == "__main__":
    customer = generate_customer()
    print(f"Customer Info: {customer}\n")
    print(generate_dialogue(1000))  # 1000 lines = 500 exchanges
