import random
from faker import Faker
import logging

fake = Faker()

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')


def generate_customer():
    amount = round(fake.pyfloat(min_value=500.01, max_value=10000, right_digits=2, positive=True), 2)
    return {
        "id": fake.uuid4(),
        "name": fake.name(),
        "phone": fake.phone_number(),
        "email": fake.email(),
        "date": fake.date(),
        "account_number": fake.bban(),
        "location": fake.city(),
        "money_amount": f"£{amount}"
    }


def generate_dialogue(customers, total_lines=50):
    if total_lines % 2 != 0:
        total_lines += 1

    scenarios = {
        "fraud": {
            "customer": [
                "My account shows charges I didn't make!",
                "I'm furious someone stole my card details.",
                "You need to fix this now—I’m scared!",
                "This is fraud and you're not doing enough!",
                "Why aren't these reversed yet?",
                "I trusted this bank—this shouldn't have happened.",
                "I’m losing sleep over this. Fix it, please!",
                "Every day this isn't resolved is agony.",
                "How could this go unnoticed by your system?",
                "You’re supposed to protect my money!",
                "Someone emptied my savings account—how?!",
                "This has completely disrupted my life.",
                "I don't feel safe keeping money here anymore.",
                "Why wasn't I notified immediately?",
                "This feels like a complete betrayal.",
                "No one is giving me straight answers!",
                "I can’t believe this happened to me.",
                "Are you even investigating this seriously?",
                "Your fraud detection clearly failed.",
                "How do I know this won’t happen again?",
                "This has ruined my financial plans.",
                "I can't access my own money—this is terrible.",
                "What if more charges appear tomorrow?",
                "My bills are overdue because of this.",
                "I’m emotionally drained from this ordeal.",
                "I expected better from a reputable bank.",
                "I need answers—this is unacceptable.",
                "I want proof you're taking this seriously.",
                "Your delay is costing me more money!",
                "No one is following up with me.",
                "This should have been resolved already.",
                "I’m tired of being put on hold.",
                "You can’t keep brushing me off!",
                "It’s been days—I’m getting desperate.",
                "I’ve never felt so helpless financially.",
                "Why was my card still active?",
                "Your system should’ve flagged this instantly.",
                "Every time I call, I get a new excuse.",
                "This is causing strain in my personal life.",
                "I’m afraid to use my account at all now.",
                "Is anyone competent handling this?",
                "My children’s tuition is at risk because of this!",
                "I had travel plans that are now ruined.",
                "This is affecting my mental health.",
                "This needs to be escalated immediately.",
                "You're lucky I'm not contacting the media.",
                "I need to speak to a supervisor now.",
                "I want this all in writing!",
                "I’m documenting every interaction from now on.",
                "You better compensate me for all this stress."
            ],
            "bank": [
                "We're deeply sorry and will begin investigating immediately.",
                "Your safety is our top priority—I'm freezing your account now.",
                "You will not be held responsible for fraudulent charges.",
                "We understand your fear, and we're acting fast.",
                "I’ve escalated this to our fraud department.",
                "Please know we take fraud cases very seriously.",
                "You’ll receive an update within 24 hours.",
                "We’re monitoring your account closely from now.",
                "I’ll send a detailed report to your email now.",
                "We understand how stressful this is—we’re with you.",
                "We’re working closely with our fraud team to resolve this.",
                "Your account has been fully secured as of now.",
                "A fraud specialist will contact you shortly.",
                "We're reimbursing all unauthorized transactions.",
                "We’ll make sure this never happens again.",
                "Your complaint is being fast-tracked.",
                "You should receive a confirmation within the hour.",
                "We're flagging this activity for future alerts.",
                "Our deepest apologies—this is not typical.",
                "We’ve opened a priority case on your behalf.",
                "We’re here with you through every step.",
                "You're right to be upset—let us fix this.",
                "Please allow us to make this right.",
                "We’ll handle all paperwork for reimbursements.",
                "I’m personally overseeing your case.",
                "We’re crediting your account for the losses.",
                "We’ve locked down any suspicious access.",
                "You’re not alone—this is high priority.",
                "I’ll get back to you as soon as I hear anything.",
                "The transactions have been reversed.",
                "You’ll receive full documentation via email.",
                "We’ve added additional security to your profile.",
                "Expect a secure call from our fraud team.",
                "We're assigning a fraud investigator right now.",
                "Let’s confirm all your recent activity.",
                "Please change your online banking credentials.",
                "Your refund is being processed today.",
                "We're taking this extremely seriously.",
                "You’ll never be charged for what you didn’t authorize.",
                "We’ve suspended all card activity as a precaution.",
                "I’ll provide a case ID for your records.",
                "We’re filing a police report if needed.",
                "We’re restoring your balance immediately.",
                "You're protected under our fraud guarantee.",
                "We’re reviewing account access logs now.",
                "A supervisor is now reviewing your file.",
                "Expect ongoing status updates every 4 hours.",
                "We’re elevating this to executive review.",
                "Your peace of mind is our top concern."
            ]
        },
        "card_issue": {
            "customer": [
                "My card keeps getting declined—it’s humiliating.",
                "I lost my card and no one is helping!",
                "Your ATM ate my card—I’m furious.",
                "The chip on my card is not working anymore.",
                "How do I even pay my bills without a card?",
                "This is seriously affecting my day-to-day.",
                "I feel stranded with no access to my funds.",
                "This delay is completely unacceptable!",
                "Why didn’t anyone tell me the card was expiring?",
                "Do I need to switch banks to get proper service?",
                "My whole weekend was ruined because I couldn't use my card!",
                "I’m embarrassed—I had to leave groceries at checkout.",
                "This is the third time this has happened. Enough is enough!",
                "I’m angry and frustrated beyond words.",
                "It’s not just inconvenient—it’s affecting my job.",
                "I had to borrow money because your card failed again!",
                "Do you understand how humiliating this is?",
                "I’m starting to think this bank just doesn’t care.",
                "Your systems are unreliable, and I’m suffering for it.",
                "My rent bounced because of this issue!",
                "This level of service is unacceptable for any bank.",
                "Your ATM error has thrown my whole month off.",
                "I’m so done explaining this over and over again.",
                "Your inaction is costing me real money and stress.",
                "I can’t sleep knowing my money is stuck.",
                "I have to carry cash everywhere now—it's not safe!",
                "What if I had an emergency? I'd be helpless!",
                "This feels like I’m being punished for trusting you.",
                "It’s beyond frustrating—I feel helpless.",
                "I’ve called three times—why is this not fixed yet?",
                "I can’t access my money but you still charge me fees?",
                "You’ve left me financially paralyzed.",
                "Do you even test your cards before sending them out?",
                "Your system errors made me miss a medical bill.",
                "This kind of service is emotionally exhausting.",
                "Your customer support is robotic and unhelpful.",
                "You act like this is a minor issue—it’s not!",
                "This card failure has ruined my entire week.",
                "Your negligence is unacceptable.",
                "It’s like shouting into a void—nobody listens.",
                "My trust in this bank is shattered.",
                "I’ve had it with the constant apologies and no action.",
                "I want real help, not just empty words!",
                "Fix it before I take my business elsewhere.",
                "I'm fed up—I want a supervisor now!",
                "This delay has caused me actual harm.",
                "Your bank is supposed to support me, not ruin me.",
                "You should be ashamed of this level of service.",
                "This situation has caused me a panic attack.",
                "I feel like screaming—nothing works!"
            ],
            "bank": [
                "I’m issuing a replacement immediately—no worries.",
                "We apologize for the inconvenience, a card is on its way.",
                "You can use virtual card access in the meantime.",
                "We’ll reimburse any fees from the ATM issue.",
                "You’ll have your new card within 2–3 business days.",
                "I'm really sorry you’re experiencing this.",
                "We’ve flagged your case as high priority.",
                "We appreciate your patience—thank you.",
                "I can walk you through setting up mobile payments.",
                "Let me waive your monthly fee to make up for this.",
                "I totally understand how frustrating this must be.",
                "We’ve launched an urgent ticket to resolve this.",
                "I’m personally monitoring your case now.",
                "Let’s fix this now so you’re not stranded again.",
                "You deserve better and we’re here to make it right.",
                "We’re adding compensation for the trouble you’ve faced.",
                "I’ll make sure your new card is sent overnight.",
                "You won’t be charged for any of these issues.",
                "Your concerns are valid—we’re truly sorry.",
                "Thank you for staying calm—we’ll fix this quickly.",
                "I’ve informed my manager—we’ll escalate this immediately.",
                "I’ll stay on the line until this is completely resolved.",
                "We’re reviewing why this wasn’t flagged earlier.",
                "Expect a confirmation email in the next few minutes.",
                "I’ve prioritized this with our operations team.",
                "You’ll receive real-time updates on progress.",
                "Let’s work together to ensure this never happens again.",
                "Your case is now marked as emergency level.",
                "We’re logging all issues and improving our process.",
                "We truly value your trust and regret this experience.",
                "We’ll track your replacement card until it arrives.",
                "I’m submitting your feedback directly to leadership.",
                "We’re working around the clock on card reliability.",
                "You should never have had to go through this.",
                "I’ll file a report and follow up within the hour.",
                "We’re reinforcing support for all cardholders.",
                "Thank you for letting us make this right.",
                "I’ll personally text you when the card ships.",
                "We’re prioritizing you until this is 100% resolved.",
                "We’re issuing a $50 goodwill credit for your trouble.",
                "We’ve taken steps to prevent this from recurring.",
                "You're right—we should’ve done better.",
                "Your peace of mind matters to us.",
                "We're contacting all impacted customers to improve.",
                "You can count on us to see this through.",
                "Please accept our sincerest apology.",
                "We’ll overnight your card at no charge.",
                "You have every right to be upset, and we’re taking action."
            ]
        },
        "login_problem": {
            "customer": [
                "I’ve been locked out of my account all day!",
                "The app won’t recognize my face ID anymore!",
                "I forgot my password and the reset isn't working!",
                "I didn’t get my verification text—again!",
                "Why do I have to call every time I can’t log in?",
                "This is ruining my ability to manage my money.",
                "I'm trying to pay bills and can't get in!",
                "I’m beyond frustrated with this app.",
                "Do you test the login feature at all?",
                "I feel completely shut out of my finances!",
                "I’ve missed payments because of this login failure!",
                "I had to spend hours just to check my balance!",
                "How can I trust a bank that locks me out constantly?",
                "Your login system is a nightmare!",
                "I feel like I’m being punished for using your app.",
                "My stress level is through the roof thanks to this!",
                "I’ve been crying over this all morning—it’s that bad.",
                "Nothing I try works—why is this so hard?",
                "I feel like I'm talking to a wall!",
                "This situation has triggered my anxiety again!",
                "It’s like you don’t care about people with issues logging in.",
                "I’ve reset my password five times—nothing helps!",
                "I’m on the verge of switching banks over this.",
                "This has ruined my weekend!",
                "Why can’t I just access my own money?!",
                "I'm beyond disappointed with your digital experience.",
                "I've tried calling, emailing, and chatting—no fix yet!",
                "This is financial lockout and it’s unacceptable!",
                "Every update just makes things worse!",
                "Your app should come with a warning label!",
                "This glitch is making me miss deadlines!",
                "I’ve lost hours of work trying to access my account.",
                "You clearly don’t test before deploying changes.",
                "Do you know how scary it is to be locked out of your finances?",
                "This isn't just a bug—it's negligence!",
                "I'm done wasting my time with your tech failures!",
                "I can’t believe how poor your service is!",
                "I'm so angry I can't even think straight!",
                "I’ve never felt so powerless—fix this!",
                "This issue is damaging my credit score!",
                "I need access NOW, not in 24 hours!",
                "I’m losing trust in your bank entirely.",
                "Every day this continues, I lose more control.",
                "Is anyone even working on this issue?",
                "I shouldn’t have to beg to access my money!",
                "My frustration is turning into rage!",
                "You’ve officially lost my confidence.",
                "Fix your app before you lose all your customers!",
                "This login hell is ruining my life!",
                "If this isn’t resolved soon, I’m closing my account."
            ],
            "bank": [
                "Let me help you regain access immediately.",
                "I’ve reset your login—try again now.",
                "We’re upgrading security systems; I’m really sorry.",
                "We’ll verify your identity and restore access.",
                "Try using the desktop login while we fix the app.",
                "I totally understand your frustration.",
                "We’re fixing this with our IT team as we speak.",
                "You’re not alone—we’re seeing this with others too.",
                "We’re documenting this to prevent future issues.",
                "Thank you for your patience—help is on the way.",
                "Let’s walk through recovery together—it won’t take long.",
                "I’m staying on the line until this is resolved.",
                "I’ll file a complaint on your behalf to escalate.",
                "Your concern is legitimate and we’re taking it seriously.",
                "You’ll receive a follow-up email within 10 minutes.",
                "We’ve prioritized your ticket with the IT team.",
                "I can see how stressful this is, and I’m here to help.",
                "We’ll send you a one-time access link now.",
                "You’re doing the right thing by contacting us.",
                "I’ve flagged your account for monitoring.",
                "We’ve logged your feedback and are updating the app.",
                "This issue is unacceptable and we agree with you.",
                "Please give us a moment—we’re correcting the backend error.",
                "You should have full access in the next 15 minutes.",
                "We’re rolling out a fix in the next software update.",
                "Thanks for bringing this to our attention—it’s crucial.",
                "We’ve seen similar reports and are deploying a solution.",
                "You're not alone—many customers are facing this, and we’re working urgently.",
                "I’ve just escalated your case to a login specialist.",
                "We’ve disabled security lockout temporarily to help you log in.",
                "You’ll receive a call shortly from our tech team.",
                "We’ve deployed a patch—please try now.",
                "I can help you set up multi-factor authentication manually.",
                "We’ll reimburse any late fees caused by this access issue.",
                "I’m forwarding this directly to our lead engineer.",
                "You’ve been patient—we really appreciate it.",
                "We’re working nonstop to resolve this.",
                "We’re deeply sorry—this should never have happened.",
                "I’m opening a real-time chat with engineering support for you.",
                "We’ll ensure this doesn’t happen again.",
                "I’ve extended your session to prevent another lockout.",
                "Expect a fix to be deployed within the hour.",
                "Let me personally notify you once access is restored.",
                "You’ll receive priority alerts from now on.",
                "I’m committed to solving this for you today.",
                "Our top developer is now assigned to your case.",
                "We’ll keep you updated every step of the way.",
                "You’ll have uninterrupted access moving forward."
            ]
        },
        "loan_application": {
            "customer": [
                "Why was my loan denied? I have good credit.",
                "I’m upset—I needed that loan for an emergency.",
                "I submitted everything but haven’t heard back!",
                "This delay is putting my plans at risk!",
                "You promised a decision in 24 hours!",
                "This is affecting my ability to relocate.",
                "You’ve left me in limbo—I deserve an answer.",
                "I feel ignored by your loan officers.",
                "I’ve been a loyal customer—this is disappointing.",
                "You said pre-approved—was that a lie?",
                "I’m so stressed—I can’t wait anymore!",
                "You’re jeopardizing my home purchase!",
                "Why is this taking so long? I did my part.",
                "Your process is confusing and exhausting.",
                "Every day without an update increases my anxiety.",
                "I feel like I’m being punished for trusting your bank.",
                "Is anyone even working on my file?",
                "I’ve sent multiple emails—no response!",
                "You said 'quick approval'—this is not quick!",
                "My entire future is on hold because of you!",
                "I’m losing sleep over this.",
                "This delay could cost me my dream apartment.",
                "Your communication is terrible and unprofessional.",
                "I feel completely abandoned in this process.",
                "What was the point of pre-approval then?",
                "I’m embarrassed I told my family it was approved.",
                "This is not how a bank should treat customers.",
                "Your process is unfair and lacks transparency.",
                "I’m tired of waiting—I need clarity now.",
                "Why advertise fast loans when they take weeks?",
                "I’m seriously considering closing my account.",
                "This entire ordeal has been demoralizing.",
                "You’ve made a hard time even harder.",
                "I had better expectations from this institution.",
                "I’ve been nothing but honest—why the silence?",
                "You’ve stalled every step of the way.",
                "I'm angry and confused—this makes no sense.",
                "It feels like you don't care at all.",
                "This situation is beyond frustrating.",
                "I have bills and deadlines—what now?",
                "Your vague answers aren’t helping me.",
                "Do you understand how serious this is for me?",
                "I’ve lost faith in your lending department.",
                "You made promises you didn’t keep.",
                "I deserve better treatment from my bank.",
                "This stress is affecting my health.",
                "You’re making a crisis even worse.",
                "I can't believe how dismissive you’ve been.",
                "I've done everything right—why am I still waiting?",
                "I feel powerless and anxious."
            ],
            "bank": [
                "I understand and I’ll look into your application personally.",
                "We’ll prioritize your file and give you a clear update today.",
                "I'm escalating this to the loan department manager.",
                "We’re very sorry for the delay and stress this has caused.",
                "I can help you explore other loan options right now.",
                "We’re reviewing your documents again for reconsideration.",
                "I will call you as soon as we get an update.",
                "Let me schedule a follow-up with our credit team.",
                "We really value your trust—we’ll make this right.",
                "I’ll advocate for your case to move it forward faster.",
                "You’re right—this wait has gone on too long.",
                "Thank you for your patience—we’re fixing this now.",
                "We’ve launched an internal review of your case.",
                "We’ll waive your application fee for the inconvenience.",
                "Your concerns are absolutely valid.",
                "Let me ensure a senior officer sees your file today.",
                "You’ll receive a personal call from our lending team.",
                "We truly regret this experience and want to help.",
                "I’m pushing this to the top of the review queue.",
                "Let’s work together to get this resolved fast.",
                "You deserve timely updates—we’ll do better.",
                "We’ll provide a decision by end of day today.",
                "We’re investigating what caused the delay.",
                "You’ll be the first to know once we hear anything.",
                "We can pre-schedule funding options in case of approval.",
                "I’ll send you a status update every 2 hours until resolved.",
                "This is now marked urgent in our system.",
                "We’ve escalated your file to the director of lending.",
                "I understand how serious this is—we’re acting now.",
                "Let’s get this sorted so you can move forward.",
                "I’m assigning a dedicated loan officer to your case.",
                "We’ve added your case to our high-priority tracker.",
                "Thank you for your patience—we won’t let this slide.",
                "We’ve updated our system to flag this kind of delay.",
                "You’ll receive a written explanation shortly.",
                "I’m coordinating directly with underwriting.",
                "You will not be left in the dark again—we promise.",
                "We value your relationship and are committed to resolving this.",
                "We are making your loan our top priority.",
                "I’ll keep you in the loop every step of the way.",
                "We’re working late today to finalize reviews like yours.",
                "We know this is time-sensitive—we’re moving quickly.",
                "Expect a status email shortly—I’ve pushed it through.",
                "We’ll offer extended support hours just for you today.",
                "You're absolutely right to demand better.",
                "We’ve restructured our queue to handle urgent files like yours.",
                "We’ll make sure this doesn’t happen again.",
                "We’re sorry for the breakdown in communication.",
                "Thank you for bringing this to our attention—we’re correcting it now."
            ]
        },
        "overdraft_fee": {
            "customer": [
                "Why was I charged an overdraft fee?!",
                "That $35 charge overdrew me even more!",
                "I had money—your system is wrong!",
                "I’m so angry about this unfair charge!",
                "This is the third time this happened!",
                "You’re charging me for your own delay!",
                "This feels predatory—I’m not rich!",
                "That one transaction ruined my budget.",
                "I’m tired of calling about the same issue.",
                "Please remove the charge—I’m begging you.",
                "How is it fair to penalize me like this?",
                "I can’t afford these fees every month!",
                "Your system mistakes are costing me dearly.",
                "This overdraft fee is ruining my credit score.",
                "I trusted this bank to protect me!",
                "I feel trapped in an endless cycle of fees.",
                "Why wasn’t I warned before charging this?",
                "This is financially devastating for my family.",
                "I’m furious and disappointed in your service.",
                "You’ve taken money I don’t have.",
                "I have bills to pay—this fee is crushing.",
                "You need to fix this immediately.",
                "Why is your system so unreliable?",
                "This charge is making me reconsider my accounts.",
                "I’m embarrassed to admit I can’t cover this.",
                "Your fees feel like a trap for struggling customers.",
                "I’m on a fixed income—this fee is unfair.",
                "I shouldn’t have to fight for my own money.",
                "Why do you make it so hard to get help?",
                "This feels like a scam disguised as banking.",
                "I’m overwhelmed by these unexpected fees.",
                "This overdraft is a huge setback for me.",
                "I expected better from a bank this size.",
                "I’m calling again because you didn’t fix it last time.",
                "I’m at my wit’s end with these charges.",
                "You’re profiting off my financial mistakes.",
                "I’m worried this will keep happening.",
                "Your customer support isn’t resolving this.",
                "I can’t keep up with these surprise fees.",
                "This is robbing me of my financial peace.",
                "I’ve followed all your rules and still got charged.",
                "This overdraft has me feeling hopeless.",
                "You’re damaging my relationship with your bank.",
                "Why do you keep letting this happen to me?",
                "I’m begging for a permanent solution here.",
                "I don’t feel like a valued customer anymore.",
                "These fees are unfair and unjustified.",
                "I want this fee reversed and assurance it won’t happen again.",
                "Your policies are hurting people like me.",
                "Please help me avoid overdrafts in the future.",
                "I can’t take this financial stress any longer."
            ],
            "bank": [
                "I understand—it looks like a timing issue, let me fix it.",
                "We’ll waive the fee as a courtesy right now.",
                "I see what happened, and I’m really sorry.",
                "We’re reviewing this with our billing team.",
                "I’ll refund the overdraft fee immediately.",
                "Let me add a temporary buffer to prevent this again.",
                "You're right—it shouldn't have happened.",
                "I'll personally make sure this is corrected today.",
                "This isn't the experience we want you to have.",
                "We're issuing a goodwill credit to your account.",
                "Thank you for bringing this to our attention.",
                "We want to help you avoid this in the future.",
                "Let me explain how our overdraft protection works.",
                "We’re improving our alerts to notify you sooner.",
                "I’ll escalate this to waive any related fees.",
                "You deserve clear communication from us.",
                "We’re here to support you through this.",
                "I’ll monitor your account for any further issues.",
                "Let’s set up overdraft protection tailored for you.",
                "I’m sorry for the stress this caused you.",
                "You have our commitment to fix this promptly.",
                "We’re reviewing your recent transactions carefully.",
                "Your feedback is helping us improve our services.",
                "I’ll personally follow up once this is resolved.",
                "We want to regain your trust.",
                "You won’t be charged for similar fees moving forward.",
                "I’m arranging a one-time fee reversal for you.",
                "We’ll send you alerts before any overdraft occurs.",
                "Let me show you tools to help monitor your balance.",
                "We’ve made changes to prevent this kind of error.",
                "I’m confident we can prevent this from recurring.",
                "Thank you for your patience and understanding.",
                "I’m escalating this issue to our senior management.",
                "Your case is a priority for us now.",
                "We’re committed to making this right.",
                "Let me assist you with budgeting resources as well.",
                "We know unexpected fees are frustrating.",
                "I’ll check your account to ensure no further fees apply.",
                "We’re setting up alerts customized to your spending.",
                "I appreciate you contacting us immediately.",
                "We want to be a bank you can depend on.",
                "I’m here to answer any questions you have.",
                "We take responsibility for this mistake.",
                "We’re improving our system to catch these errors.",
                "You should never feel penalized unfairly.",
                "I’m arranging a call with a specialist if you like.",
                "Let’s work together to find a solution.",
                "You are important to us and we care about your experience.",
                "We’ll provide a written confirmation of the refund.",
                "I’m available to assist you anytime with account concerns.",
                "Thank you for giving us the chance to fix this."
            ]
        },
        "mobile_app_problem": {
            "customer": [
                "Your app keeps crashing—it’s so frustrating!",
                "I can’t deposit checks because of the app bugs!",
                "I’m fed up with how unreliable the app is.",
                "Why does it always freeze at login?",
                "This app is ruining my banking experience!",
                "Do you even test updates before releasing them?",
                "The app update made things worse!",
                "I’m switching banks if this continues.",
                "It's unacceptable in 2025 to have these issues.",
                "You said it was fixed last week—it's not!",
                "Every time I try to transfer money, the app crashes.",
                "I lost important transactions due to app errors.",
                "The loading times are unbearable.",
                "I can't check my balance without the app freezing.",
                "Notifications don’t show up anymore.",
                "This app is unreliable and unprofessional.",
                "I’m tired of reinstalling the app every week.",
                "Your app has made me miss bill payments.",
                "Why is the app so buggy after every update?",
                "I’m embarrassed to recommend this bank with such an app.",
                "The app is draining my phone battery insanely fast.",
                "Why won’t the app remember my login info?",
                "Features keep disappearing without explanation.",
                "I can’t access customer support through the app.",
                "This app is causing me real financial headaches.",
                "I feel stuck with no alternative but to wait.",
                "You promised improvements but nothing changed.",
                "The UI is confusing and hard to navigate.",
                "It’s like the app was made without any real testing.",
                "My phone crashes every time I open the app.",
                "I’m losing trust in your digital services.",
                "Why is the app slower than the website?",
                "It’s like using an app from 10 years ago.",
                "I need mobile banking to work flawlessly—this is unacceptable.",
                "I’m fed up with being your app’s beta tester.",
                "Every update breaks something else.",
                "I want compensation for the inconvenience this app causes.",
                "Why can’t I deposit checks or send money reliably?",
                "I’m thinking about closing my account because of this app.",
                "This app is costing me time and money.",
                "It’s embarrassing that a big bank can’t fix their app.",
                "I’m frustrated beyond words with the constant crashes.",
                "I wish you would communicate better about app issues.",
                "I’m worried about security with these app problems.",
                "This app is the worst part of my banking experience.",
                "Why don’t you have a beta program to catch these bugs?",
                "I’ve lost important financial data because of the app.",
                "I can’t believe this is still happening in 2025.",
                "The app has made me reconsider my loyalty to your bank."
            ],
            "bank": [
                "We’re rolling out a fix soon, thank you for your patience.",
                "Let’s troubleshoot now—I want this resolved for you.",
                "I’ll escalate this to our app support team right away.",
                "We’re very sorry—it’s not the experience we want for you.",
                "You can use the web version while we resolve this.",
                "I understand this is affecting your experience deeply.",
                "You deserve better, and we’re fixing it.",
                "Thank you for bringing this to our attention again.",
                "We’re submitting your case to engineering directly.",
                "Our next release will address this—stay tuned.",
                "We’re aware of the crashes and working urgently.",
                "I’ll check your app version and suggest an update.",
                "Our team is testing fixes for the login freezing issue.",
                "We’ve improved the deposit feature in the latest patch.",
                "Your feedback is helping us prioritize bug fixes.",
                "I’m personally monitoring this issue for faster resolution.",
                "Please try reinstalling the app and let me know if issues persist.",
                "We’re improving app stability with every update.",
                "Thank you for your patience as we work through this.",
                "Our developers are adding more rigorous testing protocols.",
                "We’re committed to restoring your trust in our app.",
                "I’ll notify you when the fix is deployed.",
                "We’re optimizing the app’s performance for your device.",
                "I appreciate your detailed feedback—it’s very helpful.",
                "We’re expanding our support team to handle app concerns.",
                "You can contact us directly through alternative channels meanwhile.",
                "We’re reviewing the app’s battery usage issues.",
                "Our next update will improve notification reliability.",
                "We apologize for any missed payments caused by app problems.",
                "We’re making the UI more user-friendly in upcoming versions.",
                "Your case has been prioritized with our engineering team.",
                "We’re working to ensure the app remembers your login info.",
                "Security is a top priority; we’re addressing concerns immediately.",
                "Thank you for sticking with us during these challenges.",
                "We’re implementing better communication about updates soon.",
                "I’m here to assist you with any ongoing app problems.",
                "We’re testing new features to prevent further crashes.",
                "Our goal is to make mobile banking seamless for you.",
                "We understand your frustration and are dedicated to fixing it.",
                "I’ll send you a direct contact for app support escalation.",
                "Your trust is important; we won’t rest until it’s restored.",
                "We’re improving the speed and reliability of the app backend.",
                "We’re launching a customer beta program soon to catch bugs earlier.",
                "Let me know if you want help switching temporarily to web banking.",
                "We’re investigating the causes of the crashes thoroughly.",
                "I’m confident you’ll see improvements in the next update.",
                "Thanks for your continued feedback—it helps us improve.",
                "We value your loyalty and are sorry for the inconvenience.",
                "Please update the app regularly for the latest fixes.",
                "We’ll keep you updated on our progress and fixes.",
                "Your satisfaction is our priority—we’re on it."
            ]
        },
        "wire_transfer": {
            "customer": [
                "Where is my international wire? It’s been 5 days!",
                "I’m panicking—those funds were urgent!",
                "You told me it would be 24 hours!",
                "I needed that money for my family overseas!",
                "Why can’t anyone give me a straight answer?",
                "This delay is putting everything at risk!",
                "My recipient is in trouble because of this!",
                "I feel like I’m being ignored here.",
                "You said it was sent—where is it then?",
                "I’m furious—this is unacceptable!",
                "I trusted your bank with a large transfer and this is happening.",
                "The tracking info is useless—what's really going on?",
                "Why am I left in the dark about my own money?",
                "This delay is causing real harm to my loved ones.",
                "I’ve called multiple times with no clear answers.",
                "I need this resolved immediately.",
                "Your service is costing me peace of mind.",
                "You promised quick transfers, but this is a disaster.",
                "My financial plans are falling apart because of this.",
                "It’s embarrassing to rely on such poor service.",
                "I feel helpless and frustrated every day.",
                "How do you expect me to trust you again?",
                "I’m considering switching banks after this.",
                "You need to improve your international wire process.",
                "This has never happened before—why now?",
                "I’m losing money because of these delays.",
                "No one seems accountable for this issue.",
                "I want a full explanation and a solution.",
                "Please escalate this to someone who can help.",
                "The delay is causing me real emotional distress.",
                "I’m worried my funds might be lost.",
                "Your lack of communication is unacceptable.",
                "I need transparency and immediate updates.",
                "I’m counting on this money and you’re failing me.",
                "Every day without funds is a crisis.",
                "I feel completely let down by your bank.",
                "Why isn’t this transfer prioritized?",
                "I want someone to take responsibility now.",
                "I’m beyond frustrated with the silence.",
                "My family’s wellbeing depends on this transfer.",
                "How long will I have to wait for answers?",
                "I need someone to expedite this immediately.",
                "You’re damaging my relationship with your bank.",
                "This is a critical failure in your service.",
                "I demand faster resolution and accountability.",
                "My trust in your bank is shattered.",
                "Please fix this before it gets worse.",
                "I expect compensation for this delay.",
                "Your incompetence is costing me dearly."
            ],
            "bank": [
                "We’re investigating with the receiving bank immediately.",
                "Your transfer was processed—we’ll track it down now.",
                "I'm truly sorry—let’s find and resolve this fast.",
                "You’ll receive a callback within the next hour.",
                "We’re applying an urgent trace request for your transfer.",
                "We’ve opened a case and assigned it top priority.",
                "I'm monitoring this personally—I'll keep you updated.",
                "You’ll get a confirmation as soon as we have answers.",
                "This shouldn’t have happened—we take full responsibility.",
                "We’re crediting your account a fee refund due to this.",
                "Our team is working round-the-clock on this issue.",
                "We’re liaising directly with SWIFT to expedite.",
                "I appreciate your patience while we resolve this.",
                "We’re prioritizing your case above all others.",
                "Please rest assured we’re doing everything possible.",
                "I’ll update you as soon as we get news.",
                "We apologize deeply for this delay.",
                "Your satisfaction is important; we’re on it.",
                "We’re reviewing our processes to prevent recurrence.",
                "You’ll receive a detailed status report shortly.",
                "We understand the urgency and are acting accordingly.",
                "Your funds are safe; we’re just clarifying the delay.",
                "Our specialists are dedicated to resolving this.",
                "Thank you for bringing this to our attention promptly.",
                "We’re increasing our monitoring of international wires.",
                "We’re committed to restoring your confidence.",
                "I’ll personally oversee the resolution of your transfer.",
                "We’re improving communication for cases like this.",
                "You can contact me directly for updates.",
                "We’ve escalated this to senior management.",
                "We’re coordinating with correspondent banks urgently.",
                "We know how important this is for you.",
                "Your case is being treated as a critical priority.",
                "We regret the inconvenience and are making it right.",
                "Our team is expediting processing at every step.",
                "We’re implementing additional safeguards immediately.",
                "I’ll follow up with you personally after each update.",
                "We appreciate your understanding during this time.",
                "Our goal is to resolve this as quickly as possible.",
                "We’re reviewing all transfers to catch potential issues.",
                "You have our commitment to fix this promptly.",
                "Please accept our apologies and assurance of action.",
                "We’re dedicated to transparency throughout this process.",
                "We’re issuing you a goodwill credit for the trouble.",
                "Your trust matters—we’ll earn it back.",
                "We’re enhancing our international transfer systems.",
                "Thank you for your patience and continued trust.",
                "We’ll notify you immediately when resolved.",
                "Your satisfaction and security are our priorities."
            ]
        }
    }

    scenario_name = random.choice(list(scenarios.keys()))
    customer_lines = scenarios[scenario_name]["customer"]
    bank_lines = scenarios[scenario_name]["bank"]

    logging.info(f"Selected scenario: {scenario_name}")

    used_cust = []
    used_bank = []
    dialogue = []

    for i in range(total_lines):
        if i % 2 == 0:
            available = [l for l in customer_lines if l not in used_cust]
            if not available:
                used_cust = []
                available = customer_lines
            line = random.choice(available)
            used_cust.append(line)
            dialogue.append(f"Customer: {line}")
        else:
            available = [l for l in bank_lines if l not in used_bank]
            if not available:
                used_bank = []
                available = bank_lines
            line = random.choice(available)
            used_bank.append(line)
            dialogue.append(f"Bank Employee: {line}")

    # Format customer info as a string
    customer_info_text = (
        f"Customer ID: {customers['id']}\n"
        f"Name: {customers['name']}\n"
        f"Phone: {customers['phone']}\n"
        f"Email: {customers['email']}\n"
        f"Date: {customers['date']}\n"
        f"Account Number: {customers['account_number']}\n"
        f"Location: {customers['location']}\n"
        f"Money Amount: {customers['money_amount']}\n"
    )

    # Combine customer info and dialogue lines
    return f"{customer_info_text}\n" + "\n".join(dialogue)
